### ISSUE TITLE
Call PersistentData::assert_matches_layout() from a calitptra-runtime test case

### ISSUE THREAD

**Issue by korran** [chipsalliance/caliptra-sw#1185]
The PersistentData struct has much [conditional compilation](https://github.com/chipsalliance/caliptra-sw/blob/b2f09dfdf0b03933aee5df9c42db0498f8383c70/drivers/src/persistent.rs#L54) based on the "runtime feature"

The [driver test](https://github.com/chipsalliance/caliptra-sw/blob/b2f09dfdf0b03933aee5df9c42db0498f8383c70/drivers/test-fw/src/bin/persistent_tests.rs#L10) calls PersistentData::assert_matches_layout() without the "runtime" feature. We need to make sure the layout is also correct when the "runtime" feature is enabled. I recommend adding a test case to the runtime crate that calls this with the runtime feature enabled.

**Comment by sree-revoori1** [comment]
I will add a test for this.
