### ISSUE TITLE
Need to have the ROM version/hash/digest stored and exposed to SoC

### ISSUE THREAD

**Issue by attzonko** [chipsalliance/caliptra-sw#1191]
From the F2F discussion, it came up that currently the ROM version/hash/digest is not being stored and is not available to the SoC.
This is needed for both FIPS compliance and for 3rd party auditability.

**Comment by nquarton** [comment]
https://github.com/chipsalliance/caliptra-sw/pull/1257 adds this to the runtime FwInfo command. This was the solution discussed at the F2F. This, however, does not apply to ROM since ROM development has been frozen for awhile.
