### ISSUE TITLE
[FMC][ROM] FHT.rt_fw_entry_point field should be the entry index into the data vault

### ISSUE THREAD

**Issue by rusty1968** [chipsalliance/caliptra-sw#121]
FMC specification is defining   FHT.rt_fw_entry_point as the physical address of the entry point of Runtime FW Module in ICCM SRAM, however ROM is already making this information available in the  data vault.   

The proposal is to pass RT entry point field  as the entry index instead of a physical address.

**Comment by FerralCoder** [comment]
I think this is the right way to go. If the address is already protected in the DV, it would be better (safer) to use it from there.
