### ISSUE TITLE
Newly-allocated FHT fields are not invalid.

### ISSUE THREAD

**Issue by bluegate010** [chipsalliance/caliptra-sw#1236]
In the [FirmwareHandoffTable struct](https://github.com/chipsalliance/caliptra-sw/blob/809ed5ec8a5f5e963c56190028ed035dca7cf135/drivers/src/hand_off.rs#L220), the reserved field is zeroed by default. However, the sentinel value indicating that a HandOffDataHandle is invalid is u32::MAX. This causes HandOffDataHandle::is_valid() to always return true for fields that were not explicitly populated by ROM.

**Comment by bluegate010** [comment]
#1235 addresses this.

**Comment by FerralCoder** [comment]
Fixed by [1262 ](https://github.com/chipsalliance/caliptra-sw/pull/1262) instead
