### ISSUE TITLE
Driver halts upon attempting to access an invalid HandOffDataHandle field.

### ISSUE THREAD

**Issue by bluegate010** [chipsalliance/caliptra-sw#1237]
HandOffDataHandle's [try_into function](https://github.com/chipsalliance/caliptra-sw/blob/809ed5ec8a5f5e963c56190028ed035dca7cf135/drivers/src/hand_off.rs#L92) halts if it encounters certain errors. Instead, it should bubble the error to the caller and let them decide whether to halt.

**Comment by sree-revoori1** [comment]
Done in https://github.com/chipsalliance/caliptra-sw/pull/1238
