### ISSUE TITLE
Check if FMC CDI/privkey can be erased from RT

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-sw#1273]
During disable attestation we clear the RT alias key. Ideally we would also clear the FMC alias key, but since it is locked I don't know if this is possible.

Also, either we would need to repopulate the FMC CDI/privkey once we delete it (if possible) or make FMC tolerate the fact that it's not populated.

We should experiment on verlator and/or FPGA to see if this works.

**Comment by sree-revoori1** [comment]
I don't think this is possible. When I try to erase the FMC CDI or FMC priv key, I get an DRIVER_KV_ERASE_USE_LOCK_SET_FAILURE error as expected.

**Comment by jhand2** [comment]
Ok, makes sense. Closing.
