### ISSUE TITLE
FATAL/NON_FATAL wrt the error codes

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-sw#1279]
FW_ERROR_FATAL/NON_FATAL registers are entered with error code values by F/W for different errors can you point out which of the listed error codes in below link are Fatal and which are Non-Fatal?
https://github.com/chipsalliance/caliptra-sw/blob/main/error/src/lib.rs

**Comment by bluegate010** [comment]
There's not really a strong mapping between error codes and whether they're fatal or non-fatal. In some cases it's context-dependent. For example, an image validation error encountered during cold-boot would be fatal, but a validation error encountered during hitless update would be non-fatal.
