### ISSUE TITLE
How IDEVID MANUF HSM IDENTIFIER is used to reconstruct certificate

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-sw#1402]
It is mentioned in CAliptra main spec:
Caliptra does not allocate fuses in its fuse map for the IDevID certificate signature. Caliptra allocates "IDEVID MANUF HSM IDENTIFIER" fuses that the vendor can use to aid certificate reconstruction.

How IDEVID MANUF HSM IDENTIFIER can be used to reconstruct certificate?

Regards
Rahul

**Comment by varuns-nvidia** [comment]
Please don't file the same issue in multiple repositories.

**Comment by RJMJJJ** [comment]
Earlier some queries initially filed in rtl repo were answered in sw repo so I filed. But this can be closed.
