### ISSUE TITLE
Error recovery policy  for boot flow

### ISSUE THREAD

**Issue by rusty1968** [chipsalliance/caliptra-sw#141]
Don't need to decide in this PR, but if something fails during boot we probably want to do one of

1. Try again to boot from rom (maybe invoke an impactless reset?)
2. Notify the SoC and then wait for a new firmware image

This is probably something to discuss with the group.

_Originally posted by @jhand2 in https://github.com/chipsalliance/caliptra-sw/pull/135#discussion_r1157879582_

**Comment by FerralCoder** [comment]
Can this be closed?

**Comment by mhatrevi** [comment]
Nothing additional needs to be done here for the current ROM release, closing the issue.
