### ISSUE TITLE
Fixes merged for 1.1 are not applied to a 1.0 branch

### ISSUE THREAD

**Issue by nquarton** [chipsalliance/caliptra-sw#1498]
Affecting **BOTH** ROM and Runtime FW:
ECC384 KAT verify error uses wrong error code - https://github.com/chipsalliance/caliptra-sw/pull/1467
SHA384 KAT error code - https://github.com/chipsalliance/caliptra-sw/pull/1479
Pairwise Consistency Check error code is not used - https://github.com/chipsalliance/caliptra-sw/pull/1475
Partial reversal of pairwise consistency check change - https://github.com/chipsalliance/caliptra-sw/pull/1483

Affecting **ONLY** Runtime FW:
RT KAT failure change - https://github.com/chipsalliance/caliptra-sw/pull/1488

**Comment by jhand2** [comment]
Could you add the [Caliptra 1.0.x Backport](https://github.com/chipsalliance/caliptra-sw/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Caliptra+1.0.x+Backport%22) label to these PRs? That's how I've been marking PRs that need to be cherry-picked so far.

**Comment by nquarton** [comment]
> Could you add the [Caliptra 1.0.x Backport](https://github.com/chipsalliance/caliptra-sw/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Caliptra+1.0.x+Backport%22) label to these PRs? That's how I've been marking PRs that need to be cherry-picked so far.

Oh for sure, I didn't realize this existed. Thanks!
