### ISSUE TITLE
[feature] Test impactless reset flow from runtime firmware

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-sw#150]
* Implement impactless update mailbox command
* Add integration test for impactless reset

**Comment by jhand2** [comment]
More details:

* Relevant spec section on [Hitless Update](https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md#hitless-update)
* RT firmware could verifify the image before invoking reset to ensure update is actually valid

**Comment by flanfly** [comment]
Hi. I'm trying to better understand what needs to be done here. Is the issue only for implementing the mailbox command itself, i.e. parse the incoming data and call an existing function? Also what's the exact algorithm for measuring the firmware update? Do I simply extend PCR 4-8 (what's PA btw?) with the whole image? In both cases can I (re)use code that implements the passive mode for signature verification?

**Comment by jhand2** [comment]
> Is the issue only for implementing the mailbox command itself, i.e. parse the incoming data and call an existing function?

I think yes

> Also what's the exact algorithm for measuring the firmware update

After more thought, I think it makes more sense to just let ROM do the verification. See https://github.com/chipsalliance/caliptra-sw/pull/330

Today, ROM is just doing ECDSA verification ([here](https://github.com/chipsalliance/caliptra-sw/blob/main/rom/dev/src/flow/update_reset.rs#L63)). But LMS verification is also being added.
