### ISSUE TITLE
Interface for SoC ROM to stash measurements for use in DPE

### ISSUE THREAD

**Issue by andreslagarcavilla** [chipsalliance/caliptra-sw#152]
Material stashed includes ROM patches, SoC FMC

**Comment by jhand2** [comment]
I think this is also covered by https://github.com/chipsalliance/caliptra-sw/issues/100

**Comment by mhatrevi** [comment]
This is also covered by https://github.com/chipsalliance/caliptra-sw/issues/100. Closing as duplicate.
