### ISSUE TITLE
SHA512 Accelerator KAT needed

### ISSUE THREAD

**Issue by nquarton** [chipsalliance/caliptra-sw#1556]
Caliptra's SHA accelerator supports SHA512 but our KAT currently only runs a SHA384 digest. Support for 512 needs to be added in the driver and the KAT needs to be changed to run a SHA 512 digest.

NOTE: The internal SHA engine also supports SHA512 at a HW level, but this is not enabled in our driver and therefore not currently used. The plan is to leave this for now and add support at a later date.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
