### ISSUE TITLE
Need to increase MAX_ISSUER_NAME_SIZE for DPE Platform

### ISSUE THREAD

**Issue by fdamato** [chipsalliance/caliptra-sw#1558]
Caliptra hardcodes MAX_ISSUER_NAME_SIZE to 128B, which maybe very restrictive. Can this value be increased to 256B at least ?

**Comment by jhand2** [comment]
The issuer name size is just for the issuer of DPE leaf keys. In Caliptra that is always the RT alias key, which has a fixed Subject Name size. So I don't think Caliptra 1.x would ever need to support a larger name size.
