### ISSUE TITLE
Caliptra 1.0.3 Release

### ISSUE THREAD

**Issue by nquarton** [chipsalliance/caliptra-sw#1569]
Documenting steps taken for the 1.0.2 release here so they can be repeated when 1.0.3 is needed

The latest 1.0.x components are all on the branch caliptra-1.0

- [x] Create a new branch based on caliptra-1.0
- [x] Cherry-pick changes labeled with "Caliptra 1.0.x Backport"
- [x] Add one more commit that:
    - [x] Updates version numbers in version.rs
    - [x] Updates RTL submodule version if needed
- [x] Push and create a PR against the caliptra-1.0 branch
- [x] Ensure all CI passes and merge the PR (do not squash changes)
- [x] Manually trigger a nightly release on the caliptra-1.0 branch
NOTE: Publishing the test results to github will fail on any branch other than main. It may make sense to create an html page with the results as an artifact.
- [x] Re-name release as needed

**Comment by fdamato** [comment]
Let`s also update caliptra-dpe to include https://github.com/chipsalliance/caliptra-dpe/commit/3791c34f7002916d776ca906a6fc1d46abbbb163

**Comment by nquarton** [comment]
> Let`s also update caliptra-dpe to include [chipsalliance/caliptra-dpe@3791c34](https://github.com/chipsalliance/caliptra-dpe/commit/3791c34f7002916d776ca906a6fc1d46abbbb163)

I've added https://github.com/chipsalliance/caliptra-sw/pull/1575 with the backport label to track this easier.

**Comment by jhand2** [comment]
Do you also need https://github.com/chipsalliance/caliptra-dpe/pull/346? That PR looks good to me, just waiting for tests to be fixed.

**Comment by nquarton** [comment]
Release is https://github.com/chipsalliance/caliptra-sw/releases/tag/release_v20240826_0
