### ISSUE TITLE
ECC Driver does not check error regs

### ISSUE THREAD

**Issue by nquarton** [chipsalliance/caliptra-sw#1598]
The ECC driver does not check [error_global_intr_r](https://chipsalliance.github.io/caliptra-rtl/main/internal-regs/?p=clp.ecc_reg.intr_block_rf.error_global_intr_r) or [error_internal_intr_r](https://chipsalliance.github.io/caliptra-rtl/main/internal-regs/?p=clp.ecc_reg.intr_block_rf.error_internal_intr_r). These should be checked anywhere we wait on [ecc_status.valid](https://chipsalliance.github.io/caliptra-rtl/main/internal-regs/?p=clp.ecc_reg.ECC_STATUS#VALID.desc) since valid will not be set in the error case. Without this check, the ROM/FW will hang if an error is encountered.

This was noticed when forcing the public key to a bad value to cause the pairwise consistency check to fail for the FIPS tests.

**Comment by jhand2** [comment]
Agreed that we should fix this. I don't think there's a way for anyone other than the vendor to force this behavior in ROM (public keys must be fused in the manifest), but I think it can be forced in RT via the mailbox verify command.
