### ISSUE TITLE
Implement DPE and Quote API per proposal

### ISSUE THREAD

**Issue by andreslagarcavilla** [chipsalliance/caliptra-sw#161]
Will tag spec issue: https://github.com/chipsalliance/Caliptra/issues/42. Tagging as 0p8 as something will need to pair up with HW

**Comment by jhand2** [comment]
DPE implementation is complete
PCR quoting API is in progress, but https://github.com/chipsalliance/caliptra-sw/pull/429 needs to be approved/merged

**Comment by sree-revoori1** [comment]
PCR quoting/extending mailbox commands have been implemented.
