### ISSUE TITLE
Runtime FW SHALL refuse any commands coming from PAUSER 0xFFFFFFFF

### ISSUE THREAD

**Issue by fdamato** [chipsalliance/caliptra-sw#1678]
Currently Runtime FW is accepting stash measurement from PAUSER 0xFFFFFFFF, which is reserved by Caliptra as its own locality for DPE (e.g. RTJM uses it) to indicate the evidence has been measured by Caliptra itself.

**Comment by jhand2** [comment]
I think the final decision here is that we will reject any STASH_MEASUREMENT commands in Runtime that don't come from the PL0 PAUSER.
