### ISSUE TITLE
Status Command Needs to have FIPS Related Information

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-sw#186]
FIPS requires the following information:

- Module Name ASCII (Calitpra RTM)
- Version
- Mode of operation

This may require a new HW register or an expansion of the status command.

Details for this will be completed when we get FIPS consultation.

**Comment by andreslagarcavilla** [comment]
Can you file the caliptra-hw issue as well. Thanks

**Comment by JohnTraverAmd** [comment]
I can, however, this could possibly be done entirely in the Mailbox command.  I was stating that I'm not sure yet on this.

I'll file the HW issue and if we get to reject it then Yay!

**Comment by JohnTraverAmd** [comment]
For Notes related to the requirement:

- The cryptographic module shall output the name or module identifier and the versioning information that can be correlated with a validation record (e.g. hardware, software, and/or firmware versioning information).
- Versioning information (AS04.13) shall be provided for 
  - the physical single-chip including any excluded functional subsystem firmware (shall be specified in the OE field of the validation)
  - the sub-chip cryptographic subsystem soft and hard circuitry cores, and 
  - the associated firmware.

**Comment by JohnTraverAmd** [comment]
Because we are looking into having the ROM perform crypto functionality for the user, the ROM will have to perform this command.

**Comment by JohnTraverAmd** [comment]
Return Values

- Module Name ASCII = (Calitpra RTM)
- FIPS Version (HW Version | ROM Version | FW Version)
  - HW Version comes from https://chipsalliance.github.io/caliptra-rtl/main/external-regs/?p=caliptra_top_reg.generic_and_fuse_reg.CPTRA_HW_REV_ID
  - ROM Version comes from https://chipsalliance.github.io/caliptra-rtl/main/external-regs/?p=caliptra_top_reg.generic_and_fuse_reg.CPTRA_FW_REV_ID%5B0%5D
  - FW Version comes from https://chipsalliance.github.io/caliptra-rtl/main/external-regs/?p=caliptra_top_reg.generic_and_fuse_reg.CPTRA_FW_REV_ID%5B0%5D
- Mode of operation
  - Boolean FIPS Approved/Non-Approved (Defaulted to FIPS Approved)

**Comment by rusty1968** [comment]
The ROM version information should be written to the first word of the array by ROM  and runtime should populate the second word. Any objections?

**Comment by JohnTraverAmd** [comment]
I think that works.
