### ISSUE TITLE
Create SoC-side reference implementation of the mailbox protocol for Caliptra integrators

### ISSUE THREAD

**Issue by rusty1968** [chipsalliance/caliptra-sw#187]

**Comment by varuns-nvidia** [comment]
Could be covered by https://github.com/chipsalliance/caliptra-sw/issues/137?

**Comment by rusty1968** [comment]
What I am thinking is something that would be consumed by firmware developers , not the DV (RTL) validators.  it would not have HwModel as a dependency.

**Comment by korran** [comment]
I think this reference implementation should be able to be tested against the C API in #137.

**Comment by FerralCoder** [comment]
libcaliptra has been created to address this
