### ISSUE TITLE
Update ROM spec to correct owner key flow

### ISSUE THREAD

**Issue by bluegate010** [chipsalliance/caliptra-sw#238]
As identified by @varuns-nvidia in https://github.com/chipsalliance/caliptra-sw/issues/222#issuecomment-1530770019.

The ROM spec has a [flowchart](https://github.com/chipsalliance/caliptra-sw/blob/main/rom/dev/README.md#preamble-validation-steps) that includes details on owner key verification. These details should be updated:

* If owner key fuses are not populated, the owner key is not compared with them.
  * Many devices will not have these fuses populated, to support circular economy.

In addition, we should consider allowing an edge where the image has no owner key, in which case no such verification is performed.

**Comment by jhand2** [comment]
@mhatrevi should we change this for the 1.0 spec?

**Comment by bluegate010** [comment]
> In addition, we should consider allowing an edge where the image has no owner key, in which case no such verification is performed.

Just noting that this edge was never implemented; the image must always be signed by an owner key.
