### ISSUE TITLE
Vendor signature also covers owner signed data

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-sw#297]
If I'm reading the image verification code correctly, the vendor signature also covers the OwnerSignedData. I think this is problematic because that means the owner can't change the data independently without getting it signed by the vendor. Am I missing something?

cc @bluegate010

**Comment by bluegate010** [comment]
Indeed, [owner_data](https://github.com/chipsalliance/caliptra-sw/blob/39ad569a0ad976893fd654043d9f2f925e238e88/image/types/src/lib.rs#L344) is within `ImageHeader`, which is [hashed](https://github.com/chipsalliance/caliptra-sw/blob/39ad569a0ad976893fd654043d9f2f925e238e88/image/verify/src/verifier.rs#L314) to produce the digest verified against the vendor signature.

Suggest we have the vendor signature only cover the `ImageHeader` fields up to but not including `owner_data`.

As an aside, we should probably expand `OwnerSignedData` with some padding bytes, for future-proofing.
