### ISSUE TITLE
ROM Self-Integrity Check

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-sw#313]
**Requirement**: ROM will perform a self-integrity check before accepting any input from outside Caliptra Mailbox (MB).  Failure will cause all Caliptra Functionality to return Errors.

**Details:**
ROM will perform a self-integrity check performing a SHA-2-256 from (ROM Base Address) until (ROM Base Address + ROM Size - SHA_size).  ROM will then compare the SHA-2 result with the last 256 bits of the ROM to verify that the SHA-2 result is identical.

ROM build code will add the SHA-2 result onto the end of the image when completing the ROM build process.

Run-time FW will be able to perform the same command when requested by the corresponding MB command.

**Error Handling**
Upon failure, Caliptra will enter an error state and return ROM_INTEGRITY_ERROR for any MB commands.  Error handler will ensure that the MB SHA support is disabled.

**Comment by mhatrevi** [comment]
https://github.com/chipsalliance/caliptra-sw/pull/505
