### ISSUE TITLE
KBKDF Used in the HMAC derivation of the DICE Layers

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-sw#323]
Requirement: The HMAC operation which occurs on the UDS value and on the similar value for all subsequent layers must be a KBKDF operation.

**Comment by JohnTraverAmd** [comment]
Need to verify that this PR completed the work. https://github.com/chipsalliance/caliptra-sw/pull/372

**Comment by bluegate010** [comment]
Also https://github.com/chipsalliance/caliptra-sw/pull/423. Note that an SP 800-108 KDF cannot be used when deriving the LDevID CDI, due to hardware limitations when the label/context data comes from a KV slot.

**Comment by JohnTraverAmd** [comment]
We are going to close this as completed based on the work in these PRs. https://github.com/chipsalliance/caliptra-sw/pull/423 https://github.com/chipsalliance/caliptra-sw/pull/372
