### ISSUE TITLE
FIPS MB Command to Zeroize All Data/Keys

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-sw#326]
Requirement: FIPS MB Command to Zeroize All Data/Keys

Details:
A MB command is required to support zeroizing of all keys and data within the FIPS module.

**Comment by JohnTraverAmd** [comment]
https://github.com/chipsalliance/caliptra-sw/issues/324

**Comment by JohnTraverAmd** [comment]
Because we are investigating ROM services in a FIPS boot mode, ROM needs to support this message.

**Comment by JohnTraverAmd** [comment]
This command will need to support EOL vs a power off case.

**Comment by JohnTraverAmd** [comment]
Expected behavior:

- Clear Data Vault
- Clear data memory (handoff table, etc.)

Send a completion response.
Then, enter an error loop which rejects all commands with error.

A test which confirms that we are sending errors on further commands.
This may be the disable attestation command - https://github.com/chipsalliance/caliptra-sw/tree/main/runtime#disable_attestation

**Comment by JohnTraverAmd** [comment]
@jhand2 do you think this requirement is fulfilled in the https://github.com/chipsalliance/caliptra-sw/tree/main/runtime#disable_attestation command?

**Comment by jhand2** [comment]
One note about clearing data memory: If we do this, this will also prevent us from doing any hitless/warm resets. Once FHT, certs, etc are cleared, we can only fully repopulate them on cold boot.

This might be fine, just want to call that out.

**Comment by JohnTraverAmd** [comment]
I see.  That makes sense.  

I think that could be the difference between these two commands.  The FIPS Zeroize command would NOT want to support a Hitless FW update and be able to continue.  Its goal is to ensure all internal data is zeroized.  We can have both commands and have different functionality there, I just didn't want to duplicate the same behavior.

**Comment by rusty1968** [comment]
Some data vault entries are locked by the ROM. We can't erase all entries in RT.

**Comment by rusty1968** [comment]
@jhand2 , we need to acknowledge the completion of shutdown via maiilbox and write to non-fatal error (if fatal error register is better than we can do that). guess it is report_error_and_halt then.
