### ISSUE TITLE
Change ECC_SIG_VERIFY Command to ECC_SIG_VERIFY_PRIMITIVE

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-sw#327]
Requirement: Change ECC_SIG_VERIFY Command to ECC_SIG_VERIFY_PRIMITIVE

Since the MB Command is receiving the SHA of the data that was signed, this command is only a primitive and not a full ECC Signature full Verify.  It needs to be labeled correctly.

**Comment by jhand2** [comment]
The raw data is streamed to Caliptra via the sha384 accelerator. Does that change anything?

**Comment by JohnTraverAmd** [comment]
It may, where is that described?

**Comment by jhand2** [comment]
https://github.com/chipsalliance/caliptra-sw/blob/main/runtime/README.md#ecdsa384_signature_verify

**Comment by JohnTraverAmd** [comment]
This was the location that we reviewed.  Did it change recently?

**Comment by JohnTraverAmd** [comment]
I see that it did change.  https://github.com/chipsalliance/caliptra-sw/commit/45a8493a12b7d6bc9c5207d43068957035a0704a

I will re-review this new change with the FIPS consultant and see if it meets the requirement now.

**Comment by swkeypair** [comment]
The ECDSA Sig Ver operation is now all performed within the module. It is definitely the case that SW libraries perform security functions piecemeal (e.g. a hash operation, then the verification math) but the caller must perform the operations in the right sequence. 

I would like to get lab input on this, but given that the hash is on the module, this should be OK.
