### ISSUE TITLE
If ECC or LMS validation fails, the exact reason for the failure is lost

### ISSUE THREAD

**Issue by korran** [chipsalliance/caliptra-sw#335]
https://github.com/chipsalliance/caliptra-sw/blob/fe6cd119d29e6e1159a6e75a53a28b3b9c6f3f23/image/verify/src/verifier.rs#L316-L319

At the very least, the original failure reason should be saved somewhere for debugging purposes.

**Comment by mhatrevi** [comment]
Fix: Copy the error code in extended info.
