### ISSUE TITLE
[LMS] E2E integration tests

### ISSUE THREAD

**Issue by mhatrevi** [chipsalliance/caliptra-sw#344]

**Comment by satyamsetti** [comment]
We have a signing and verification test. Not sure if that counts.

**Comment by korran** [comment]
We need a set of tests end-to-end integration tests that are equivalent to all these ECC ones:

https://github.com/chipsalliance/caliptra-sw/blob/main/rom/dev/tests/test_image_validation.rs#L290

**Comment by satyamsetti** [comment]
We added them in https://github.com/chipsalliance/caliptra-sw/pull/397
so closing them now

**Comment by satyamsetti** [comment]
Leaving this for vmhatrevi to close.
