### ISSUE TITLE
Setting ROM region as cacheable in MRAC - Cause RISC-V to throw an exception on FPGA 

### ISSUE THREAD

**Issue by fdamato** [chipsalliance/caliptra-sw#345]
On FPGA, setting ROM region as cacheable in MRAC causes RISC-V to throw "invalid operation" exception. 
When the exception is triggered, the MEPC register points to the PC location where the the MRAC register is set.
While, the issue doesn`t present on Verilator, an investigation should be performed to rule out an actual RTL cause.

**Comment by jlmahowa-amd** [comment]
We are likely running into FPGA specific issues.
When the illegal instruction exception is fired mtval gets stored with the instruction.
mtval: 0x**a0b7**9073
Supposed to be: 0x**7c00**9073

A slightly different ROM binary with identical setup code running on the same FPGA image does not reproduce this illegal instruction exception.

**Comment by jlmahowa-amd** [comment]
This was resolved by fixing the FPGA frequency.
