### ISSUE TITLE
ROM code size exceeds 32KB

### ISSUE THREAD

**Issue by ChiaweiW** [chipsalliance/caliptra-sw#355]
Hi All,

I used the `rom/dev/build.sh` script to construct Caliptra ROM binary. (commit: f3b4ee23f5971c6cb5574320b37c93997a977281)
However, the `caliptra-rom` binary size is 72KB, which excceds the ROM size 32KB described in the HW spec.
[Caliptra_HW_Block_diagram.png](https://github.com/chipsalliance/Caliptra/blob/main/doc/images/Caliptra_HW_Block_diagram.png)

Did I miss something during the build? Any guidance is appreciated.

Regards,
Chiawei

**Comment by jhand2** [comment]
The output binary is an ELF file. Only the `.text` and `.rodata` sections actually make up the ROM image size (stack, bss, etc occupy DCCM RAM).

You can see the sections and sizes with `readelf -S caliptra-rom`

**Comment by ChiaweiW** [comment]
After `make objcopy` under rom/dev/, the generated binary is padded to exactly 32KB.
Thanks a lot for your help.
