### ISSUE TITLE
Consider moving all long-lived DCCM structures to one region

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-sw#356]
Currently, the linker script specified several regions for storing certs, PCR log, fuse log, etc. in DCCM. The suggestion is to instead have one region in DCCM for the FHT and move all of those other things into that struct.

For example:

```rust
struct HandoffTable {
  ...
  ldevid_cert: [u8; MAX_CERT_SIZE];
  fmc_alias_cert: [u8; MAX_CERT_SIZE];
  rt_alias_cert: [u8; MAX_CERT_SIZE];
  fuse_log: [FuseLogEntry; MAX_FUSE_LOG_ENTRIES];
  pcr_log: [PcrLogEntry; MAX_PCR_LOG_ENTRIES];
  ...
}
```

There would be a single region defined in the linker script to hold all this data. And we can implement a driver for accessing it.

cc @mhatrevi @rusty1968 @korran

**Comment by FerralCoder** [comment]
I think this proposal makes sense.

**Comment by rusty1968** [comment]
I will take this one.

**Comment by rusty1968** [comment]
@mhatrevi , @jhand2  : this requires some refactoring as now we are instantiating make_fht in the stack - maybe we need to get together and make sure we have enough tests to make this a safe refactor.

**Comment by rusty1968** [comment]
@korran  , @vsonims

**Comment by jhand2** [comment]
+1 to that recommendation

**Comment by korran** [comment]
Everyone is happy with the solution in https://github.com/chipsalliance/caliptra-sw/blob/main/drivers/src/persistent.rs
