### ISSUE TITLE
HW Release: Caliptra C API package provided as part of the supporting ZIP File

### ISSUE THREAD

**Issue by fdamato** [chipsalliance/caliptra-sw#391]
The Caliptra C API Library should be distributed in the collateral supporting ZIP File, as part of the HW Release.
The provided APIs should allow the SOC to interact with Caliptra, through (included but not limited to) mailbox communication.
The library would need to be compiled by the integrator in their environment, they would need to:
         - Implement SOC interface functions which will perform the SOC-specific Caliptra operations
               `void apb_write(uint32_t address, uint32_t data);`
                `uint32_t apb_read(uint32_t address);`
         - Provide PATH to their cross compiler

**Comment by wmaroneAMD** [comment]
Reassigned to myself. I've linked my branch on my fork of caliptra-sw.

**Comment by wmaroneAMD** [comment]
I think this is done.
