### ISSUE TITLE
MB Command Parameter Checking

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-sw#424]
MB Command Parameter Checking

When a MB command is not providing correct parameters, the MB will reject the command as INVALID_PARAMETERS.

**Comment by rusty1968** [comment]
FMC does not handle mailbox commands. Are there any planned?

**Comment by JohnTraverAmd** [comment]
No. FMC shouldn't service any mailbox commands. Just ROM and runtime.

**Comment by rusty1968** [comment]
Why the FMC label?

**Comment by rusty1968** [comment]
Thanks for removing it :-)

**Comment by JohnTraverAmd** [comment]
Possible Errors:

- Reject for Unsupported Command
- Reject for Size
- DPE Parameter Commands Invalid if inaccurate.

Test Created that runs some invalid commands for each error case added.

**Comment by rusty1968** [comment]
ROM : Firmware download command is checking parameters. Stash measurement is still in progress.

**Comment by mhatrevi** [comment]
1. FIRMWARE_LOAD:  
- Checks for if dlen is not 0 or not greater than the max. image size.
- Verifier library validates the image.

2. VERSION
3. SELF_TEST_START 
4. SELF_TEST_GET_RESULTS 
5. SHUTDOWN 
6. CAPABILITIES 
7. STASH_MEASUREMENT
- Verifies checksum of the command with the value in the command header.
- Verifies dlen matches the data received.
-
