### ISSUE TITLE
ROM should clear SHA512 LOCK explicitly at startup

### ISSUE THREAD

**Issue by calebofearth** [chipsalliance/caliptra-sw#431]
SHA512 accelerator was recently changed to initialize with LOCK = 1 (see https://github.com/chipsalliance/caliptra-rtl/issues/58).
~ROM currently does not clear the LOCK before trying to use the SHA512 accelerator.~
EDIT: ROM currently attempts to acquire the LOCK before trying to use the SHA512 accelerator, even though it already owns the lock.

**Comment by mhatrevi** [comment]
The fix for this will be checked in when the RTL change makes it to main branch.
