### ISSUE TITLE
Consider logging fatal errors in CPTRA_FW_ERROR_NON_FATAL as well

### ISSUE THREAD

**Issue by mhatrevi** [chipsalliance/caliptra-sw#453]

**Comment by korran** [comment]
The idea here is that some vendors will likely create a "run_mailbox_command" abstraction in their SoC logic, and they may not realize they need to check CPTRA_FW_ERROR_NON_FATAL or CPTRA_FW_ERROR_FATAL (depending on the context of the command) to figure out why their mailbox command failed.

**Comment by korran** [comment]
If we always put the reason for the mailbox command failure into CPTRA_FW_ERROR_NON_FATAL, even if it was a fatal error, that increases the chances that the reason for failure gets logged somewhere.

**Comment by FerralCoder** [comment]
Can this be closed?

**Comment by mhatrevi** [comment]
This has been addressed by https://github.com/chipsalliance/caliptra-sw/pull/665.
