### ISSUE TITLE
Refactor Mailbox Driver Drop Trait Implementation

### ISSUE THREAD

**Issue by vsonims** [chipsalliance/caliptra-sw#47]
The drop trait implementation needs to be unwrap free. Currently the Mailbox Drop implementation is panicking due to unwraps. We should not be making any calls that results in unwraps to be called.

**Comment by FerralCoder** [comment]
@mhatrevi can this be closed?

**Comment by mhatrevi** [comment]
Closing as this issue is no longer applicable.
