### ISSUE TITLE
Fuse driver using `fmc_key_manifest_svn` fuse as `fmc_svn`

### ISSUE THREAD

**Issue by bluegate010** [chipsalliance/caliptra-sw#480]
The FuseBank [fmc_svn()](https://github.com/chipsalliance/caliptra-sw/blob/26fb69901e49b2fe50fe1547e75558e4051edbff/drivers/src/fuse_bank.rs#L219) accessor is using the `fmc_key_manifest_svn` fuse under the hood, which could be misleading. It might make sense to ask that this fuse be renamed, for clarity. Checking here before filing an issue in caliptra-rtl.

**Comment by mhatrevi** [comment]
fmc_svn() accessing fmc_key_manifest_svn is correct. Ok with fuse being renamed for clarity.
