### ISSUE TITLE
RT SVN fuse is four words wide, but only two words are used by the driver

### ISSUE THREAD

**Issue by bluegate010** [chipsalliance/caliptra-sw#481]
The FuseBank [runtime_svn()](https://github.com/chipsalliance/caliptra-sw/blob/26fb69901e49b2fe50fe1547e75558e4051edbff/drivers/src/fuse_bank.rs#L235) accessor is using two words, but there are [four](https://chipsalliance.github.io/caliptra-rtl/main/internal-regs/?p=clp.soc_ifc_reg.fuse_runtime_svn%5B0%5D) words in this fuse's array. Should the driver count the zeroes across all four words?

**Comment by mhatrevi** [comment]
This was by design. Synced with @vsonims; we'll update this to use all the words.
