### ISSUE TITLE
FPGA: Reduce bringup complexity of FPGA by eliminating Kernel modules

### ISSUE THREAD

**Issue by jlmahowa-amd** [chipsalliance/caliptra-sw#485]
FPGA uses two kernel modules to give access to FPGA memory space. One module is for register IO and the other is for the ROM backdoor.
All of physical memory is accessible using /dev/mem, and so that could be used to simplify deployment by removing the need for loading the kernel modules on each boot.

Concern: Can /dev/mem be accessed without root?

**Comment by mhatrevi** [comment]
Closing as no plans to do this.
