### ISSUE TITLE
sw-emulator does not properly set fuse ready bit in status

### ISSUE THREAD

**Issue by wmaroneAMD** [chipsalliance/caliptra-sw#508]
The sw-emulator does not properly set GENERIC_AND_FUSE_REG_CPTRA_FLOW_STATUS_READY_FOR_FUSES_MASK in CALIPTRA_TOP_REG_GENERIC_AND_FUSE_REG_CPTRA_FLOW_STATUS. This was confirmed to be an emulator issue by enabling verilator and polling the same bit, which happens immediately.

This test was done using the libcaliptra hwmodel example (currently in PR), which defaults to the sw-emulator. Rebuilding the model and binding with --features verilator and rebuilding the example (and enabling the currently disabled initial poll of the fuse bit) we poll the bit and immediately pass the check. In the software simulator it fails.

Of note, the following line appears on the verilated output:

`4,100 ready_for_fuses is high`

This line is never seen in the sw-simulator, I do not know if it should be.

**Comment by fdamato** [comment]
In the init_fuses method of the HW Model implementation we are not checking for ready for fuses, and that`s why this issue was probably never exposed
