### ISSUE TITLE
SW emulator does not support warm reset

### ISSUE THREAD

**Issue by jlmahowa-amd** [chipsalliance/caliptra-sw#540]
SW-emulator currently does not support warm reset. There is not a way to trigger the emulator from the hw-model any warm reset behavior.

In sw-emulator/lib/periph/src/soc_reg.rs it is unclear how warm reset support should be handled.
// [TODO] Enable warm reset after design agreement.
In addition what code exists seems to be triggered by Caliptra writing the generic output register, rather than an outside entity being able to toggle the reset signal.

**Comment by korran** [comment]
Srinath offerred to take this on;

**Comment by srinathshiv** [comment]
A pull request for this issue will be raised within a few days
