### ISSUE TITLE
Findings from fuzzing x509

### ISSUE THREAD

**Issue by benjamindoron** [chipsalliance/caliptra-sw#581]
Attempting to fuzz x509 shows that `Ecdsa384CertBuilder::build()` returns certs that OpenSSL's `X509::from_der()` will throw errors trying to parse. I'm trying to determine if I'm even fuzzing correctly here.

For example, `tbs [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 119, 255, 255, 255, 255, 105, 15, 41, 105, 114, 97, 32, 73, 101, 118, 41, 68, 48, 71, 73, 48, 95, 101, 95, 95, 95, 95, 95, 95, 95, 95, 95, 48, 118, 48, 16, 0, 0, 0, 0, 0, 0, 0, 254, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 122, 91, 91, 91, 91, 91, 95, 95, 95, 95, 95, 101, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 147, 95, 95, 95, 95]` and `sig Ecdsa384Signature { r: [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 209, 209, 209, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 209, 47, 46, 46, 46, 209, 209, 209, 209, 209, 209, 0, 0, 0], s: [0, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 122, 0, 0, 255, 255, 0, 0, 0, 0, 0, 255, 255, 95, 95, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 255, 0, 0] }`

Returns:
`buf [48, 130, 1, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 119, 255, 255, 255, 255, 105, 15, 41, 105, 114, 97, 32, 73, 101, 118, 41, 68, 48, 71, 73, 48, 95, 101, 95, 95, 95, 95, 95, 95, 95, 95, 95, 48, 118, 48, 16, 0, 0, 0, 0, 0, 0, 0, 254, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 122, 91, 91, 91, 91, 91, 95, 95, 95, 95, 95, 101, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 147, 95, 95, 95, 95, 48, 10, 6, 8, 42, 134, 72, 206, 61, 4, 3, 3, 3, 103, 0, 48, 100, 2, 49, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 209, 209, 209, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 209, 47, 46, 46, 46, 209, 209, 209, 209, 209, 209, 0, 0, 0, 2, 47, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 122, 0, 0, 255, 255, 0, 0, 0, 0, 0, 255, 255, 95, 95, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 255, 0, 0]`

**Comment by jhand2** [comment]
The fuzz input here is used as the TBS directly, so the output is not valid ASN.1. Instead I think we should fuzz the inputs to the cert templating (IDevID, LDevID, FMC Alias, and RT). I'll see if I can tweak the current tests to do this.
