### ISSUE TITLE
Implement structure-aware fuzzing

### ISSUE THREAD

**Issue by benjamindoron** [chipsalliance/caliptra-sw#624]
Rather than taking a byte slice as an argument, we can take any struct, and the input will be mutated to match the struct types. In theory, this helps pass more validation checks.

Another use case is automating the process of preparing multiple sets of function arguments. For instance, the DPE fuzzing target could fuzz the support matrix, whether this can lead to undefined behaviour.

Implementing this is a matter of making relevant structs and their internals conditionally derive `Arbitrary` from the crate that performs this mutation.

**Comment by benjamindoron** [comment]
It doesn't seem like I can assign myself, though I am working on this.

**Comment by benjamindoron** [comment]
Done for image verifier and LMS, I've been told to wait regarding further work.

**Comment by korran** [comment]
Completed
