### ISSUE TITLE
Move ROM integrity tests to a shared crate

### ISSUE THREAD

**Issue by rusty1968** [chipsalliance/caliptra-sw#682]
ROM  integrity tests need to be invoked by runtime.
https://github.com/chipsalliance/caliptra-sw/blob/e62d770179dee0a4a452ee5f42ba7547a80a41c2/rom/dev/src/main.rs#L154

**Comment by FerralCoder** [comment]
closed by https://github.com/chipsalliance/caliptra-sw/pull/693

**Comment by FerralCoder** [comment]
The actual function rom_integrity_test() was not moved because the rom and runtime versions need to do slightly different things. But the underlying image verification code was made common
