### ISSUE TITLE
Sha384Acc::lock() locks the register with a write instead of a read (as the register docs mention)

### ISSUE THREAD

**Issue by korran** [chipsalliance/caliptra-sw#708]
Noticed by NCC:

https://github.com/chipsalliance/caliptra-sw/blob/8b23c0a6d1fb727c932d2f84b9ca4aa543214da8/drivers/src/sha384acc.rs#L83-L86

This contradicts the [register docs](https://chipsalliance.github.io/caliptra-rtl/main/external-regs/?p=caliptra_top_reg.sha512_acc_csr.LOCK):

> SHA lock register for SHA access, reading 0 will set the lock, Write 1 to clear the lock

**Comment by korran** [comment]
Sha384::lock() is only used in fatal error handling, and I believe the intention there is to forcibly steal the lock so the SoC cannot use the peripheral (required for FIPS).

**Comment by mhatrevi** [comment]
This is a documentation bug. Filed https://github.com/chipsalliance/caliptra-rtl/issues/216 to update the register doc.
