### ISSUE TITLE
IDevID CSR should be signed with vendor chip-class key in Caliptra ROM

### ISSUE THREAD

**Issue by lomax** [chipsalliance/caliptra-sw#721]
IDevID CSR creation flow by Caliptra ROM mentioned in [#294](https://github.com/chipsalliance/caliptra-sw/issues/294#issuecomment-1682641196)
> 2\. Ask Caliptra for the self-signed IDevID CSR

contradicts with current Caliptra spec https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md#idevid-key
> To mitigate man-in-the-middle attacks, Caliptra ROM shall sign the IDevID CSR with a “CSR envelope” private key. The CSR envelope private key is an ECDSA-P384 private key that is a chip-class secret provisioned by the vendor.

**Comment by varuns-nvidia** [comment]
https://github.com/chipsalliance/Caliptra/issues/40 is filed to remove this spec section. This change did not make the plan of record cut.
