### ISSUE TITLE
Add stash_measurement svn and context to the PCR log

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-sw#759]
From https://github.com/chipsalliance/caliptra-sw/pull/559#discussion_r1322020210

We want all of the additional fields from StashMeasurementReq in the log:

metadata (4 bytes)
svn (4 bytes)
context (48 bytes)

cc @bluegate010 @mhatrevi

**Comment by bluegate010** [comment]
Implemented in https://github.com/chipsalliance/caliptra-sw/pull/766

**Comment by mhatrevi** [comment]
https://github.com/chipsalliance/caliptra-sw/pull/766
