### ISSUE TITLE
Should [afmc] be [rom]?

### ISSUE THREAD

**Issue by bluegate010** [chipsalliance/caliptra-sw#788]
https://github.com/chipsalliance/caliptra-sw/blob/9f1d077f7ba1e463c23c63b50b19809209c1e74c/rom/dev/src/flow/cold_reset/fw_processor.rs#L177

**Comment by FerralCoder** [comment]
I'm not a fan of it either, but I believe that represents the fact that this is part of the Alias FMC generation flow
