### ISSUE TITLE
If a warm reset occurs while ICCM is being written during a hitless update, CPU can execute an unvalidated instruction sequence

### ISSUE THREAD

**Issue by korran** [chipsalliance/caliptra-sw#817]
After the warm reset, the CPU eventually jumps to runtime firmware that is partially written.

By controlling the amount of time before the warm reset, an attacker may be able to get the CPU to perform a dangerous operation.

**Comment by jhand2** [comment]
One potential fix:

Use the boot status to denote that fw writing is in progress.

On warm reset, first thing ROM does is check the boot status and panic if fw wasn't fully written.  Seems like a decent use-case for using a WarmResetEntry4 data vault slot.

**Comment by bluegate010** [comment]
Would another way to put that be, always perform a cryptographic validation of the image before jumping to it, even in a warm-boot flow? Not sure we need to use an extra DV slot for that.

**Comment by varuns-nvidia** [comment]
Would the DCCM image pass validation?

**Comment by korran** [comment]
We don't necessarily need a datavault slot; We could use an DCCM address in the ROM's reserved  section that we set before we start mutating ICCM and clear after we're done.

**Comment by korran** [comment]
| Would another way to put that be, always perform a cryptographic validation of the image before jumping to it,

I think this would be the best option, but I think Bharat or maybe Vishal S wanted the warm reset to occur quickly.

**Comment by bluegate010** [comment]
Ah, I misunderstood the suggestion.

**Comment by korran** [comment]
| Would the DCCM image pass validation?

I assume you mean ICCM? The mailbox contents would have been validated before the copy to ICCM started, but since the copy was interrupted you would have an attacker-controlled mixture of the new firmware and the old firmware.

Upon warm reset, we do NOT re-validate ICCM, which I think is by design, but I don't recall the reasoning for that.

**Comment by jhand2** [comment]
> We don't necessarily need a datavault slot; We could use a DCCM address in the ROM's reserved section that we set before we start mutating ICCM and clear after we're done.

I agree a data vault slot isn't strictly necessary. My only concern was if some other firmware accidentally corrupted that address, then Caliptra would be unrecoverable until next cold reset. Putting it in a lockable DV slot makes that a little more protected.

But I don't feel too strongly either way.

**Comment by korran** [comment]
> Putting it in a lockable DV slot makes that a little more protected.

Don't we need to be able to perform N hitless updates? If the DV slot is locked can't it only be used once?

**Comment by JohnTraverAmd** [comment]
I would request that we actually verify the FW hash of both the FMC and Run-time and compare it against the locked hash from the DV registers.  FMC TCI is a 48 byte register (Cold Reset Registers) and the RT TCI register (Warm Reset Register).

FIPS requires that the image is verified cryptographically after a reset.
