### ISSUE TITLE
Changes in Context Tree Affecting Behavior in Other Branches

### ISSUE THREAD

**Issue by ericeilertson** [chipsalliance/caliptra-sw#825]
The DeriveChild DPE command could be invoked in a manner which modified a parent
context in a way that might impact the derived key that is used to compute signatures
generated using contexts within other branches of a context tree.

By modifying a parent context in this way, an attacker could cause the result of a Sign
command to be computed using a different derived key pair to that used in a preceding 
CertifyKey command executed within the same context. Within an attestation flow, this
could result in the certificate chain returned by the attestation response containing a
different public key to that used to sign the attestation challenge.

If the context tree contained derived contexts from different localities, the changes could
also affect contexts across different localities.

**Comment by jhand2** [comment]
Fixed by https://github.com/chipsalliance/caliptra-dpe/pull/202
