### ISSUE TITLE
Premature Context State Modification in DeriveChild Implementation

### ISSUE THREAD

**Issue by ericeilertson** [chipsalliance/caliptra-sw#829]
Impact
The implementation of the DeriveChild command prematurely modified certain properties
of the new or parent context before it was certain that the command would succeed. This
could lead to the behaviour of the parent context changing when computing measurement
hashes or invalidating parent contexts.

Because all of the state-changing statements occurred subsequent to validation of the
supplied context handle and locality, this could not be abused to modify contexts to which
the attacker did not already have accessed, and therefore judged to carry a low overall risk.

**Comment by jhand2** [comment]
Fixed by https://github.com/chipsalliance/caliptra-dpe/issues/191
