### ISSUE TITLE
DefaultPlatform::get_certificate_chain Test Code Panics on Some Inputs

### ISSUE THREAD

**Issue by ericeilertson** [chipsalliance/caliptra-sw#831]
Test code could be used as a base for real implementation, and bugs could be propagated.
It should be noted that towards the end of the assessment, code for DpePlatform::get_certificate_chain has been merged, and it does not contain the described bug.

**Comment by jhand2** [comment]
Fixed by https://github.com/chipsalliance/caliptra-dpe/pull/169
