### ISSUE TITLE
Chunk Size and Certificate Size Misuse in GetCertificateChain Command

### ISSUE THREAD

**Issue by ericeilertson** [chipsalliance/caliptra-sw#832]
This finding does not have an impact because the values of the misused constants are
coincidentally the same. This finding is raised for informational purposes.

**Comment by jhand2** [comment]
Fixed by https://github.com/chipsalliance/caliptra-dpe/pull/169

**Comment by jhand2** [comment]
Further fix in https://github.com/chipsalliance/caliptra-dpe/pull/231
