### ISSUE TITLE
[RT Test] Test warm reset flows in RT

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-sw#881]
The DPE context is stored in DCCM and is persisted across warm resets. But the emulator doesn't support warm reset, so we don't currently have tests for this flow. We should:

* Write tests that run against FPGA
* Implement warm reset in the emulator

Ideally we would also emulate DCCM state corruption and ensure the right things happen on warm reset.

**Comment by sree-revoori1** [comment]
Closing since I have made sub-issues for the specific warm reset tests we want.
