### ISSUE TITLE
Verilator test failures: RT DPE-related failures

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-sw#882]
See https://github.com/chipsalliance/caliptra-sw/issues/851 for details

* test_disable_attestation_cmd
* test_invoke_dpe_sign_and_certify_key_cmds
* test_stash_measurement

**Comment by zhalvorsen** [comment]
test_stash_measurement is fixed by #893, but the other two are still failing

**Comment by sree-revoori1** [comment]
test_disable_attestation_cmd is fixed by https://github.com/chipsalliance/caliptra-sw/pull/933.

**Comment by zhalvorsen** [comment]
test_invoke_dpe_sign_and_certify_key_cmds  fixed by #931
