### ISSUE TITLE
ROM : Configs to make ROM jump to FMC in Debug & Security State = 0

### ISSUE THREAD

**Issue by lemonzinga** [chipsalliance/caliptra-sw#883]
In the ROM code, is it possible to skip the FIPS tests in DEBUG mode and security state set to 0x0.

I'm trying to run a very lean ROM code that does the very basic setup and then moves onto FMC->RT. 
Are there any config on SW side we need to set for this?

**Comment by JohnTraverAmd** [comment]
https://github.com/chipsalliance/caliptra-sw/pull/710. 

Once this gets merged, then it will be in the next release.

**Comment by JohnTraverAmd** [comment]
This looks like it was merged.  Have you confirmed that this has fulfilled your needs?

**Comment by lemonzinga** [comment]
The Fake ROM merge fulfills the needs specified here. Thank you! Closing this issue.
