### ISSUE TITLE
ROM : ECC-384 waits indefinitely for the VALID bit to be set

### ISSUE THREAD

**Issue by lemonzinga** [chipsalliance/caliptra-sw#884]
In our simulation environment, we used the generic trace file created by the emulation run rom/dev/ . 
- We followed the trace file output to configure the fuse values and drive the simulation.
- On ECC based operations [ECC-384 code](https://github.com/chipsalliance/caliptra-sw/blob/main/drivers/src/ecc384.rs#L439) , the program counter waits indefinitely for the VALID bit to be set. 
- Make note that Caliptra is configured for debug mode and security state set to 0x0.

What configuration needs to be in place for the successful execution of ECC operations.

**Comment by JohnTraverAmd** [comment]
Can you specify exactly which ECC operation is hanging?

**Comment by lemonzinga** [comment]
@JohnTraverAmd  @mhatrevi 
Certainly,
This is the flow we expect when the IDEVID layer executes.
In the cold reset flow -> **run -> InitDevIdLayer::derive -> generate_csr -> make_csr -> ecdsa384_sign_and_verify -> ecc384.sign -> verify -> verify_r**

This returns from the ECC operation successfully and we were able to verify that it indeed takes about ~1.3 million cycles.

This is the flow we expect when the LDEVID layer executes.
**run -> LocalDevIdLayer::derive -> generate_cert_sig -> ecdsa384_sign_and_verify -> ecc384.sign -> verify -> [verify_r](https://github.com/chipsalliance/caliptra-sw/blob/main/drivers/src/ecc384.rs#L439)**
And it is at this point where its stuck indefinitely for the VALID bit to be set( ~4million cycles and counting ).

Please let us know if there are any pre-requisites that need to satisfied for the LDEVID based ECC op to return successfully. Note : the simulation environment has been setup in DEBUG mode with the security state set to 0x0.

**Comment by mhatrevi** [comment]
@lemonzinga There are no pre-requisites for ECC as such. Is it possible to share any debugging info? (console output, waveforms etc.)

**Comment by JohnTraverAmd** [comment]
@lemonzinga Are you still having issues here?  If not, can you identify what fixed it?

If you aren't able to respond soon, we may close this.  Feel free to open it back up if there is still an issue.

**Comment by lemonzinga** [comment]
We're still having issues on this. I will ask my HW counterpart to comment on this issue and provide more debug info.

**Comment by mhatrevi** [comment]
Closing the issue as there haven't been any updates; please open a new issue when additional debug info is available.
