### ISSUE TITLE
ROM/Fake ROM to Support Integration by Booting without Random Numbers

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-sw#888]
Request is:
* Have a bit in Debug/Manufacturing register where ROM decides to skip RNG health tests for any RNG data it requires to boot if not in the production security state.

Background:
* For integration, RNG may take longer to setup and develop.  To help enable parrallel development and integration, it would be ideal to have a way to skip RNG requirements so ROM gets to ready for FW with minimal effort for the integrator.
* Another point here is that on first boot, before fuses are programmed, ROM can't hang if the random data isn't good enough.  ROM needs to be able to boot without a proper RNG configuration when not in a production state.

**Comment by mhatrevi** [comment]
Discussed with Bharat; a bit will be reserved in the Dbg. Mfg register, which when set, and only when debug mode is on, the RNG driver will return a non-zero constant (CFI needs a non-zero random number to seed its software based RNG).
