### ISSUE TITLE
Set Ready-For-FW Earlier in ROM

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-sw#890]
Set Ready For FW Earlier in ROM.

In order to help boot times for SOC, we should enable Ready For FW as soon as possible so that SOC can start loading Caliptra FW. 

A few items that may impact this decision would be: 
1. FIPS requirements to complete init before allowing input.  ROM Integrity test is a must execute here.
2. If the SOC requests IDevID CSR, Calitpra was going to own the MB to send it back.  We need to decide what would happen if CSR is requested and SOC already put FW into the MB.

**Comment by mhatrevi** [comment]
Additionally, as per the design, once the firmware load command is issued to the ROM, it does not process any other commands (e.g.: STASH_MEASUREMENT).
