### ISSUE TITLE
Ensure Runtime testing is complete

### ISSUE THREAD

**Issue by FerralCoder** [chipsalliance/caliptra-sw#905]
* Review code flows and determine if test is in place
  * Add line item to SmartSheet for review time
* Develop any identified missing tests
  * Add line item to SmartSheet for development time
* Use code coverage data to identify any unexpected gaps
  * Add line item to SmartSheet for analysis time

**Comment by jhand2** [comment]
Planned additional tests:

* Run DPE [verification](https://github.com/chipsalliance/caliptra-dpe/tree/main/verification) tests
    * Includes exercising libcaliptra code paths
    * Includes extensive X.509 testing and linting
* PCR quote/extend/reset counter APIs
* More extensive hitless update tests

I will continue to update this issue as I come up with more.
