### ISSUE TITLE
Re-enabling WDT timers requires restart bit setting

### ISSUE THREAD

**Issue by upadhyayulakiran** [chipsalliance/caliptra-sw#925]
In current design, disabling WDT timers will suspend counting, but the counters will not reset to 0. Re-enabling the timers will simply resume counting. In order to have the timers start from 0, the corresponding restart bit is required to be set. 

Example programming sequence for cascade mode for disabling and re-enabling timer1:
**Set CPTRA_WDT_TIMER1_EN to 1**
WDT timer1 starts counting
**Reset CPTRA_WDT_TIMER1_EN to 0**
WDT timer1 suspends counting
**Program CPTRA_WDT_TIMER1_TIMEOUT_PERIOD[1:0]**
**Set CPTRA_WDT_TIMER1_EN to 1**
WDT timer1 resumes counting
**Set CPTRA_WDT_TIMER1_CTRL to 1**
WDT timer1 starts counting from 0

**Comment by rusty1968** [comment]
https://github.com/chipsalliance/caliptra-sw/pull/938
