### ISSUE TITLE
error: option `recurse-submodules' takes no value

### ISSUE THREAD

**Issue by UriSha1** [chipsalliance/caliptra-sw#943]
I cannot clone caliptra-sw from repo with all dependencies.
I work in Centos 7.4 
Please help me.

**Comment by jhand2** [comment]
Hello! Can you share the exact command you ran to clone the repo?

**Comment by UriSha1** [comment]
Thanks for the reply.
I had a missing path in .cshrc file.    
set path = (/usr/local/bin/  $path
