### ISSUE TITLE
Fault injection hardening for verifier code

### ISSUE THREAD

**Issue by varuns-nvidia** [chipsalliance/caliptra-sw#982]
3 asks:
1. Ensure no constant time window between externally-visible signal and critical branch.
2. Add/confirm init-to-fail logic for boolean checks
3. Use multi-bit booleans

Details are captured in https://github.com/chipsalliance/caliptra-sw/blob/main/rom/dev/doc/threat-model.md#mitigation-2

**Comment by FerralCoder** [comment]
@mhatrevi Did we cover all the asks here? If not, the remaining items should be split out into new issues.

**Comment by mhatrevi** [comment]
> @mhatrevi Did we cover all the asks here? If not, the remaining items should be split out into new issues.

Added issue https://github.com/chipsalliance/caliptra-sw/issues/1057 and https://github.com/chipsalliance/caliptra-sw/issues/1056
